version: '2'
services:
  bot:
    image: ailinykh/reposter
    container_name: reposter
    environment:
      BOT_TOKEN: 12345678:XXXXXXXXxxxxxxxxXXXXXXXXxxxxxxxxXXX
      ADMIN_CHAT_ID: 1488
      AMQP_URL: amqp://guest:guest@localhost:5672/
    volumes:
      - ./reposter-data:/usr/local/share/reposter-data
    restart: always